name: Build Docker image

on:
  workflow_dispatch:
    inputs:
      app:
        required: true
        type: choice
        options:
          - openai-transcribe
      imageTag:
        required: true
        type: string
      buildArgs:
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.app }}/Dockerfile
          build-args: |
            ${{ inputs.buildArgs }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ftnext/${{ inputs.app }}:${{ inputs.imageTag }}
            ftnext/${{ inputs.app }}:latest
